export {
  aplicarPorcentaje,
  BASE_PUNTOS_BASICOS,
  centavos,
  CERO,
  esNegativo,
  maximo,
  minimo,
  puntosBasicos,
  restar,
  sumar,
  sumarTodos,
  type Money,
  type PuntosBasicos,
} from './money.ts';

export { calcularDistribucion, DIEZMO, type Distribucion, type EntradaCascada } from './cascada.ts';

export {
  calcularMargen,
  CATEGORIAS_DE_COSTO,
  categoriasEstimadas,
  costoEstimado,
  SIN_ESTIMAR,
  type CategoriaDeCosto,
  type CostosEstimados,
  type EntradaDelMargen,
  type MargenDelTrabajo,
} from './costos.ts';

export {
  CANTIDAD_MAXIMA,
  cantidadEditada,
  cantidadEscrita,
  catalogoDeNecesidades,
  claveDelNombre,
  cuentaDeLoQueHaceFalta,
  esNombreDeNecesidad,
  LARGO_MAXIMO_DEL_NOMBRE,
  nombreEditado,
  nombreEscrito,
  segmentosDeLoQueHaceFalta,
  sugerenciasDeNecesidad,
  SUGERENCIAS_MAXIMAS,
  TIPOS_DE_NECESIDAD,
  type CuentaDeLoQueHaceFalta,
  type NecesidadUsada,
  type NombreDelCatalogo,
  type ParaContar,
  type SegmentoDeLoQueHaceFalta,
  type TipoDeNecesidad,
} from './necesidades.ts';

export {
  claveBancariaDe,
  digitosDeCbu,
  esClaveVirtual,
  esCuentaDeMercadoPago,
  esLinkDeMercadoPago,
  formatearCbu,
  HOSTS_DE_MERCADO_PAGO,
  LARGO_DE_CBU,
  LARGO_MAXIMO_DE_ALIAS,
  LARGO_MAXIMO_DEL_LINK,
  LARGO_MINIMO_DE_ALIAS,
  normalizarAlias,
  normalizarLinkDeCobro,
  PREFIJO_DE_MERCADO_PAGO,
  revisarAlias,
  revisarCbu,
  revisarLinkDeCobro,
  verificadorDelBloque,
  type AvisoDeAlias,
  type ClaveBancaria,
  type MotivoDeAlias,
  type MotivoDeCbu,
  type MotivoDelLink,
  type RevisionDeAlias,
  type RevisionDeCbu,
  type RevisionDelLink,
} from './cobro.ts';

export {
  digitosDeCuit,
  formatearCuit,
  LARGO_DE_CUIT,
  PREFIJOS_DE_EMPRESA,
  PREFIJOS_DE_PERSONA,
  revisarCuit,
  verificadorDeCuit,
  type MotivoDeCuit,
  type RevisionDeCuit,
} from './cuit.ts';

export {
  calcularLiquidacion,
  liquidadoDelMes,
  planDeLiquidacion,
  resumenDelMes,
  SIN_DIEZMO,
  sueldoDelMes,
  topesDeLaLiquidacion,
  type AjustesDeLiquidacion,
  type EntradaLiquidacion,
  type EscalonDelMes,
  type Liquidacion,
  type LiquidacionRegistrada,
  type LiquidadoDelMes,
  type Objetivos,
  type PlanDeLiquidacion,
  type Reapertura,
  type ResumenDelMes,
  type SueldoDelMes,
  type Topes,
} from './liquidacion.ts';

export {
  calcularSena,
  porcentajeDeLaSena,
  SENA_HABITUAL,
  type EntradaDeLaSena,
  type SenaDelTrabajo,
} from './sena.ts';

export {
  conLaForma,
  formasDeCobro,
  FORMAS_DE_COBRO,
  instanciasPendientes,
  INSTANCIAS_DE_PAGO,
  montoParaPegar,
  ofrece,
  pagoQueToca,
  pagosPorDelante,
  unaSolaForma,
  type FormaDeCobro,
  type InstanciaDePago,
  type PagoPorDelante,
} from './pagos.ts';

export {
  APROBADO_SIN_LA_SENA,
  APROBASTE_EL_PRESUPUESTO,
  ARMAMOS_EL_PRESUPUESTO,
  CERRANDO_EL_PRESUPUESTO,
  comoPagar,
  COORDINAMOS_LA_ENTREGA,
  EMPEZAMOS_A_FABRICARLO,
  estaAprobada,
  FALTA_MEDIR_DEL_ESTIMADO,
  FUIMOS_A_MEDIR,
  hayComoTransferir,
  HITO_DEL_ESTIMATIVO,
  HITOS,
  llegoAl,
  LO_LLEVAMOS_Y_LO_INSTALAMOS,
  NOTA_DEL_RELEVAMIENTO,
  notaDelRelevamiento,
  O_POR_MERCADO_PAGO,
  PASOS_PARA_TRANSFERIR,
  PEDILE_LOS_DATOS,
  PRESUPUESTO_MANDADO,
  proyeccionDeLaEntrega,
  RECIBIMOS_TU_PAGO,
  relevamientoDelTrabajo,
  RESUMEN_FALTA_MEDIR,
  SIGUE,
  SIGUE_CON_EL_PRESUPUESTO_MANDADO,
  SIGUE_FALTA_LA_SENA,
  SIGUE_FALTA_MEDIR,
  SIN_FECHA_PARA_LA_VISITA,
  TE_PASAMOS_EL_ESTIMATIVO,
  TE_PASAMOS_EL_PRESUPUESTO,
  textoDeLaProyeccion,
  TITULAR_DEL_APROBADO,
  tuvoEstimativo,
  VAMOS_TOMANDO_LOS_TRABAJOS,
  vistaDelCliente,
  type ArchivoDelCliente,
  type CobroDelTaller,
  type ComoPagar,
  type CuentaParaTransferir,
  type DatosDelTrabajo,
  type EntregaDelTrabajo,
  type EstadoDelHito,
  type EstadoDelRelevamiento,
  type EtapaAprobada,
  type EtapaDeLaVista,
  type EventoDelCliente,
  type FechasDelTrabajo,
  type FocoDeLaVista,
  type FormatosDeFecha,
  type HitoDelTrabajo,
  type HitoDeLaVista,
  type NotaDelRelevamiento,
  type PagoDelCliente,
  type PagoOfrecido,
  type PagoPendiente,
  type PagoQueSigue,
  type ProyeccionDeLaEntrega,
  type RelevamientoDeLaVista,
  type SenaDeLaVista,
  type TrabajoDelCliente,
  type VisitaDelTrabajo,
  type VistaAntesDelPresupuesto,
  type VistaAprobada,
  type VistaDelCliente,
  type VistaEsperandoLaSena,
} from './vistaCliente.ts';

export {
  EN_SEGUIMIENTO,
  ESTADOS,
  ESTADOS_DE_CONSULTA,
  esEstado,
  esEstadoDeConsulta,
  estaLiquidado,
  faseDe,
  puedeCambiarEstado,
  puedeCerrarPerdido,
  puedeCobrar,
  puedeLiquidar,
  puedePasarASeguimiento,
  puedeReabrir,
  puedeReactivar,
  puedeRevertir,
  TRANSICIONES,
  type EstadoDeConsulta,
  type EstadoLiquidado,
  type EstadoProyecto,
  type Fase,
} from './estados.ts';

export {
  DIAS_HABILES_DE_ENTREGA,
  DIAS_HABILES_PARA_PRESUPUESTAR,
  diasEntre,
  entregaEstimada,
  mesDe,
  sumarDias,
  sumarDiasHabiles,
  sumarMeses,
  vencimientoDelPresupuesto,
} from './fechas.ts';

export {
  fechaDelPlazo,
  PLAZOS_DEL_SEGUIMIENTO,
  plazoDeLaFecha,
  RESULTADOS_DEL_CONTACTO,
  type PlazoDelSeguimiento,
  type ResultadoDelContacto,
} from './seguimiento.ts';

export {
  ANTICIPACIONES,
  AVISO_DE_LA_CATEGORIA,
  AVISOS_DE_LA_AGENDA,
  CATEGORIAS_DE_AGENDA,
  CATEGORIAS_DEL_TRABAJO,
  CATEGORIAS_DERIVADAS,
  CATEGORIAS_PROPIAS,
  diaPorHoras,
  eventosDeLaAgenda,
  eventosParaAvisar,
  horaDelEvento,
  HORARIO_DEL_TALLER,
  PREFERENCIAS_INICIALES,
  puedeArrastrarse,
  rangoQueEntra,
  TODO_EL_RELOJ,
  type Anticipacion,
  type AnotacionDeLaAgenda,
  type AvisoDeLaAgenda,
  type CategoriaDeAgenda,
  type CategoriaDelTrabajo,
  type CategoriaDerivada,
  type CategoriaPropia,
  type ClienteDeLaAgenda,
  type DatosDeLaAgenda,
  type DiaPorHoras,
  type EventoDeLaAgenda,
  type EventoDerivado,
  type EventoPropio,
  type FranjaDelDia,
  type PreferenciaDeAviso,
  type PreferenciasDeAvisos,
  type ProximoDeLaAgenda,
  type ProyectoDeLaAgenda,
  type RangoDeHoras,
  type RangoDeLaAgenda,
} from './agenda.ts';

export {
  comoGuardar,
  comoLaVeElCliente,
  cuantasPreguntas,
  duracion,
  elMueble,
  encuestaBase,
  enPalabras,
  envioDe,
  ESCALA_POR_DEFECTO,
  ESCALAS,
  estadoDelPedido,
  fueMandado,
  LARGO_MAXIMO_DE_LA_OPCION,
  LARGO_MAXIMO_DE_LA_PREGUNTA,
  LIMITE_DEL_LARGO_SEG,
  limpiarBorrador,
  lineasDeLaRespuesta,
  MAXIMO_DE_OPCIONES,
  menosDe,
  mesesDeHistoria,
  MINIMO_DE_OPCIONES,
  mismaForma,
  modoDeMostrar,
  nombresQueOpinaron,
  pasoDe,
  pasosDe,
  pedidosPorTrabajo,
  porcentaje,
  primeraPalabra,
  promedio,
  propiasDelTrabajo,
  PUNTOS_DE_LA_TASA,
  queTieneLaEncuesta,
  REFERENCIA_SEG,
  resumenDeOpiniones,
  revisarBorrador,
  SEGUNDOS_DE_ENTRADA,
  SEGUNDOS_POR_TIPO,
  sePuedeBorrar,
  TIPOS_DE_PREGUNTA,
  TIPOS_DE_PREGUNTA_PROPIA,
  TOPE_PREGUNTAS,
  TOPE_PROPIAS,
  UMBRAL_BARRAS,
  UMBRAL_EVOLUCION,
  UMBRAL_MESES,
  usoDeLasPreguntas,
  versionesDe,
  vigentesPorSerie,
  type Cara,
  type Comentario,
  type ComoGuardar,
  type Conteo,
  type DatosDeLasOpiniones,
  type Duracion,
  type EncuestaBase,
  type EncuestaGuardada,
  type EnvioDelTrabajo,
  type Escala,
  type EstadoDelPedido,
  type Evolucion,
  type FilaDeTrabajo,
  type FormaDePregunta,
  type Genero,
  type LineaDeLaRespuesta,
  type ModoDeMostrar,
  type Paso,
  type PedidoMandado,
  type Polo,
  type PreguntaDeLaEncuesta,
  type PreguntaEditable,
  type PreguntaGuardada,
  type ProblemaDelBorrador,
  type Promedio,
  type PuntoDeLaEvolucion,
  type RenglonGuardado,
  type RespuestaGuardada,
  type ResultadoDePregunta,
  type ResumenDeOpiniones,
  type Situacion,
  type TipoDePregunta,
  type TipoDePreguntaPropia,
  type TonoDelLargo,
  type TrabajoOpinado,
  type UsoDeLaPregunta,
  type ValorGuardado,
  type VersionAnterior,
} from './opiniones.ts';

export {
  armarRespuesta,
  esLinkDeResena,
  faltantes,
  HOSTS_DE_RESENA,
  largoDelTexto,
  LARGO_MAXIMO_DE_LA_RESPUESTA,
  LARGO_MAXIMO_DEL_LINK_DE_RESENA,
  MOTIVOS_DEL_RECHAZO,
  normalizarLinkDeResena,
  revisarLinkDeResena,
  sinBlancosEnLasPuntas,
  tieneTexto,
  validarRespuesta,
  type MotivoDelLinkDeResena,
  type MotivoDelRechazo,
  type RenglonDelFormulario,
  type RespuestaDelFormulario,
  type RevisionDelLinkDeResena,
  type ValorDelFormulario,
  type ValoresDelFormulario,
} from './encuesta.ts';

export {
  asientosDeLaLinea,
  asientosDelLibro,
  asientosDelMes,
  CATEGORIA_DE_APERTURA,
  entradasYSalidas,
  esAnteriorALaApertura,
  estadoDelDiezmo,
  fechaDeApertura,
  lineasDelLibro,
  mueveLosTesoros,
  proyeccionCocos,
  saldosDelLibro,
  saldosPorTesoro,
  TESOROS,
  type Asiento,
  type DatosDelLibro,
  type EntradasYSalidas,
  type EstadoDelDiezmo,
  type GastoDelLibro,
  type LineaDelLibro,
  type MovimientoDelLibro,
  type OrigenDeAsiento,
  type PagoDelLibro,
  type ProyectoDelLibro,
  type SaldosPorTesoro,
  type SituacionDelDiezmo,
  type Tesoro,
} from './libroMayor.ts';
