export { Avatar, colorDelNombre, inicialesDelNombre } from './components/Avatar.tsx';
export type { AvatarProps } from './components/Avatar.tsx';
export { Button } from './components/Button.tsx';
export type { ButtonProps, ButtonSize, ButtonVariant } from './components/Button.tsx';
export { Campo } from './components/Campo.tsx';
export type { CampoProps } from './components/Campo.tsx';
export { CampoDeContrasena } from './components/CampoDeContrasena.tsx';
export type { CampoDeContrasenaProps } from './components/CampoDeContrasena.tsx';
export { FilaDeAcciones } from './components/FilaDeAcciones.tsx';
export type { FilaDeAccionesProps } from './components/FilaDeAcciones.tsx';
export { Icono } from './components/Icono.tsx';
export type { IconoProps, NombreDeIcono } from './components/Icono.tsx';
export { MoneyInput } from './components/MoneyInput.tsx';
export type { MoneyInputProps } from './components/MoneyInput.tsx';
export { Pagina } from './components/Pagina.tsx';
export type { PaginaProps } from './components/Pagina.tsx';
